wandb: Currently logged in as: hadars (autoconvnext). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.13.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/s3092593/benchmarking_rl/wandb/run-20221201_015818-2zbsfzu0
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run bumbling-vortex-1
wandb: ⭐️ View project at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_NameThisGame_model_50000000_0_impala_large_4
wandb: 🚀 View run at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_NameThisGame_model_50000000_0_impala_large_4/runs/2zbsfzu0
wandb: Waiting for W&B process to finish... (success).
wandb: 
wandb: Run history:
wandb: loss █▅▅▄▄▃▄▃▄▃▃▃▂▂▃▂▂▂▂▂▂▂▂▁▁▁▁▂▁▁
wandb:  mae █▅▄▄▄▂▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂▂▂▁
wandb: 
wandb: Run summary:
wandb: loss 0.88535
wandb:  mae 2.3588
wandb: 
wandb: Synced bumbling-vortex-1: https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_NameThisGame_model_50000000_0_impala_large_4/runs/2zbsfzu0
wandb: Synced 6 W&B file(s), 0 media file(s), 1 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20221201_015818-2zbsfzu0/logs
wandb: wandb version 0.13.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/s3092593/benchmarking_rl/wandb/run-20221201_040227-2pland9y
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run astral-sun-2
wandb: ⭐️ View project at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_NameThisGame_model_50000000_0_impala_large_4
wandb: 🚀 View run at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_NameThisGame_model_50000000_0_impala_large_4/runs/2pland9y
wandb: Waiting for W&B process to finish... (success).
wandb: 
wandb: Run history:
wandb: loss █▆▅▅▄▄▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁
wandb:  mae █▅▄▄▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▂▂
wandb: 
wandb: Run summary:
wandb: loss 0.94123
wandb:  mae 2.52306
wandb: 
wandb: Synced astral-sun-2: https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_NameThisGame_model_50000000_0_impala_large_4/runs/2pland9y
wandb: Synced 6 W&B file(s), 0 media file(s), 1 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20221201_040227-2pland9y/logs
wandb: wandb version 0.13.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/s3092593/benchmarking_rl/wandb/run-20221201_060650-1onmgz8e
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run polished-field-3
wandb: ⭐️ View project at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_NameThisGame_model_50000000_0_impala_large_4
wandb: 🚀 View run at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_NameThisGame_model_50000000_0_impala_large_4/runs/1onmgz8e
wandb: Waiting for W&B process to finish... (success).
wandb: 
wandb: Run history:
wandb: loss █▆▅▅▄▃▄▃▂▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁
wandb:  mae █▅▅▄▄▂▃▃▂▃▂▁▂▂▁▂▂▂▁▁▂▁▁▂▂▂▁▁▂▂
wandb: 
wandb: Run summary:
wandb: loss 0.8842
wandb:  mae 2.41081
wandb: 
wandb: Synced polished-field-3: https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_NameThisGame_model_50000000_0_impala_large_4/runs/1onmgz8e
wandb: Synced 6 W&B file(s), 0 media file(s), 1 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20221201_060650-1onmgz8e/logs
wandb: wandb version 0.13.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/s3092593/benchmarking_rl/wandb/run-20221201_081133-2ot6ne6g
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run ethereal-plant-4
wandb: ⭐️ View project at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_NameThisGame_model_50000000_0_impala_large_4
wandb: 🚀 View run at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_NameThisGame_model_50000000_0_impala_large_4/runs/2ot6ne6g
wandb: Waiting for W&B process to finish... (success).
wandb: 
wandb: Run history:
wandb: loss █▆▅▅▅▃▄▃▂▃▂▂▂▂▁▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁
wandb:  mae █▅▅▄▄▂▃▃▂▃▃▂▂▂▁▂▂▁▂▂▁▂▂▁▂▂▁▂▂▁
wandb: 
wandb: Run summary:
wandb: loss 0.94917
wandb:  mae 2.32914
wandb: 
wandb: Synced ethereal-plant-4: https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_NameThisGame_model_50000000_0_impala_large_4/runs/2ot6ne6g
wandb: Synced 6 W&B file(s), 0 media file(s), 1 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20221201_081133-2ot6ne6g/logs
wandb: wandb version 0.13.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/s3092593/benchmarking_rl/wandb/run-20221201_101549-17iu4euw
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run happy-feather-5
wandb: ⭐️ View project at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_NameThisGame_model_50000000_0_impala_large_4
wandb: 🚀 View run at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_NameThisGame_model_50000000_0_impala_large_4/runs/17iu4euw
--- Logging error ---
Traceback (most recent call last):
  File "/data1/s3092593/rlenv/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/data1/s3092593/rlenv/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "/data1/s3092593/rlenv/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/data1/s3092593/rlenv/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 50, in run
    self._run()
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 101, in _run
    self._process(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 263, in _process
    self._hm.handle(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 130, in handle
    handler(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 138, in handle_request
    logger.debug(f"handle_request: {request_type}")
Message: 'handle_request: stop_status'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/data1/s3092593/rlenv/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/data1/s3092593/rlenv/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "/data1/s3092593/rlenv/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/data1/s3092593/rlenv/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 50, in run
    self._run()
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 101, in _run
    self._process(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 263